name: Automated tests
permissions: {}
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [
          '3.10',
          '3.11',
          '3.12',
          '3.13',
          '3.14',
          '3.15',
        ]

    steps:
    - uses: >- # v6.0.2
        actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
    - uses: >- # v8.0.0
        astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b
      with:
        python-version: ${{ matrix.python-version }}
        enable-cache: true
    - uses: >- # v3.0.1
        pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd
    - name: Install dependencies
      run: |
        uv sync --group ci
    - name: Test pinned deps with unittest
      run: |
        uv run coverage erase
        uv run coverage run -m unittest discover
    - name: Check coverage
      run: |
        uv run coverage report --show-missing --fail-under=95
    - name: Test with dependency matrix
      run: |
        uv run tox
    - name: Test build sdist and wheel packages
      run: |
        uv build
