# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, '3.10', '3.11.0-rc.2']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        if [ -f requirements.dev.txt ]; then pip install -r requirements.dev.txt; fi
    - name: Lint with flake8
      run: |
        flake8 . --count --show-source
    - name: Test pinned deps with unittest
      run: |
        coverage erase
        coverage run -m unittest discover
    - name: Check coverage
      run: |
        coverage report --show-missing --fail-under=90
    - name: Test with dependency matrix
      run: |
       tox
    - name: pypi-publish
      uses: pypa/gh-action-pypi-publish@v1.5.1
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
